# Generated by Django 4.2.13 on 2024-06-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('manager', 'manager'), ('admin', 'admin')], default='staff', max_length=10),
        ),
    ]
