# Generated by Django 4.2.13 on 2024-06-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('lead', 'lead'), ('admin', 'admin')], default='staff', max_length=100),
        ),
    ]
