# Generated by Django 4.2.13 on 2024-06-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('lead', 'lead'), ('admin', 'admin'), ('management', 'management'), ('tech_lead', 'tech_lead')], default='staff', max_length=100),
        ),
    ]
